app.host=zznote.ru

app.debug=false
zk.log.enable=false

server.error.include-binding-errors=never
server.error.include-exception=false
server.error.include-message=never
server.error.include-stacktrace=never

#bea.trm.enable=true

server.port=${PORT:80}

web.session.timeout.bycookie.min=1000000



